In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,1],[2,2,1],[1,3,1]])

In [3]:
S = np.linalg.svd(A)

In [4]:
np.linalg.norm()

(array([[-0.48821284,  0.09896983, -0.86709468],
        [-0.58022986, -0.77896859,  0.23778404],
        [-0.65190608,  0.61920345,  0.43772772]]),
 array([ 5.00016664,  0.97801738,  0.20448853]),
 array([[-0.46010039, -0.81849345, -0.34405829],
        [-0.85863904,  0.50879752, -0.06216179],
        [ 0.22593502,  0.26682121, -0.93688836]]))

In [6]:
np.linalg.norm(A[:,0])

2.4494897427831779

In [7]:
np.linalg.norm(np.matmul(S[0], A)[:,0])

2.4494897427831779